# Generated by Django 2.1 on 2018-08-24 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cls_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLS_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='course_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('students_cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_sys1.Cls_student')),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('coanhing_years', models.IntegerField()),
                ('Entry_time', models.DateField()),
                ('thear_student', models.ManyToManyField(to='Student_sys1.students')),
            ],
        ),
        migrations.AddField(
            model_name='course_1',
            name='course_stu',
            field=models.ManyToManyField(to='Student_sys1.students'),
        ),
        migrations.AddField(
            model_name='cls_student',
            name='cls_thear',
            field=models.ManyToManyField(to='Student_sys1.teachers'),
        ),
    ]
